---

- name: enable mysql
  service: name=mysqld state=started enabled=yes

- name: configure mysql
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
  notify: restart mysql

- name: set mysql root password
  mysql_user: name=root host={{ item }} password={{ sql_root_password }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost

- name: delete anonymous user
  mysql_user: user="" host={{ ansible_default_ipv4.address }} state="absent"

- name: delete anonymous user for localhost
  mysql_user: user="" state="absent"

- name: remove test database
  mysql_db: db=test state=absent
