---

- name: configure cups
  copy: src=cupsd.conf dest=/etc/cups/cupsd.conf owner=root group=lp mode=644
  notify: restart cups

- name: configure printers
  copy: src=printers.conf dest=/etc/cups/printers.conf owner=root group=lp mode=600

- name: enable cups
  service: name=org.cups.cupsd state=started enabled=yes

