---

- name: create tor group
  group: name=tor system=yes state=present

- name: create tor user
  user: name=tor group=tor createhome=no state=present system=yes

# These should eventually be uncommented (2015-04-01)
#- name: install tor installation script
#  copy: src=tor-setup.sh dest=/usr/bin/tor-setup.sh owner=root group=root mode=744

#- name: run tor setup script 
#  command: tor-setup.sh creates=/srv/tor/etc/tor/torrc

#- name: install tor service override
#  copy: src=chroot.conf dest=/etc/systemd/system/tor.service.d/chroot.conf owner=root group=root mode=644

- name: configure tor
  copy: src=torrc dest=/etc/torrc owner=root group=root mode=644

- name: set directory permissions
  file: dest=/var/lib/tor state=directory owner=tor group=tor mode=644 recurse=yes
