---

- name: configure dnsmasq
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf owner=root group=root mode=644
  notify: restart dnsmasq

- name: configure resolv
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=644

- name: configure hosts
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=644

- name: enable dnsmasq
  service: name=dnsmasq state=started enabled=yes

