---

- name: configure ssh
  copy: src=ssh_config dest=/etc/ssh/ssh_config owner=root group=root mode=644

- name: configure sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=644
  notify: restart sshd

- name: enable sshd
  service: name=sshd state=started enabled=yes

