---

- name: configure samba
  copy: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root mode=644
  notify:
    - restart smbd
    - restart nmbd

- name: create share directories
  file: dest=/srv/smb/{{ item }} state=directory
  with_items:
    - public
    - joey
    - alice
    - ashley
    - guest

- debug: var=users

- name: add users to samba database
  pdbedit: name={{ item.name }} password={{ item.pw_plain }} state=present create=yes
  with_items: users
  when: item.name != "root" or item.name != "dev"

- name: enable samba
  service: name={{ item }} state=started enabled=yes
  with_items:
    - smbd
    - nmbd
