---

- name: configure samba
  copy: src=smb.conf dest=/etc/samba/smb.conf owner=root group=root mode=644
  notify:
    - restart smbd
    - restart nmbd

- name: create share directories
  file: dest=/srv/smb/{{ item.name }} state=directory
  with_items: users

- name: enable samba
  service: name={{ item }} state=started enabled=yes
  with_items:
    - smbd
    - nmbd
